/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysadminRole.AdminRole;

/**
 *
 * @author DELL
 */


import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.EnterpriseDelivery.Delivery;
import Business.Network.Network;
import Business.Role.DeliveryAdmin;
import Business.Role.FulfillmentCenterAdmin;
import Business.Role.HubAndLastMileAdmin;
import Business.Role.VendorAdmin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;

public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    boolean a = true;
    Enterprise enterprise;
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    DeliveryAdmin delAd;
    HubAndLastMileAdmin hubAndLmAd;
    VendorAdmin venAd;
    FulfillmentCenterAdmin fcAd;
    
    public AdminWorkAreaJPanel(Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.enterprise = enterprise;
        this.system = system;
        this.system=EcoSystem.getInstance();
    }
    public AdminWorkAreaJPanel(DeliveryAdmin delAd){
        initComponents();
        this.enterprise = delAd.getDelivery();
        this.system = EcoSystem.getInstance();
        this.delAd=delAd;
    }
    public AdminWorkAreaJPanel(HubAndLastMileAdmin hubAndLmAd){
        initComponents();
        this.enterprise = hubAndLmAd.getHubAndLastMile();
        this.system = EcoSystem.getInstance();
        this.hubAndLmAd=hubAndLmAd;
    }
    public AdminWorkAreaJPanel(VendorAdmin venAd){
        initComponents();
        this.enterprise = venAd.getVendor();
        this.system = EcoSystem.getInstance();
        this.venAd=venAd;
    }
    public AdminWorkAreaJPanel(FulfillmentCenterAdmin fcAd){
        initComponents();
        this.enterprise = fcAd.getFC();
        this.system = EcoSystem.getInstance();
        this.fcAd=fcAd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);    
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        
        if(numberbool == 1){
            
            h1.setBackground(new Color(70,55,37));
            h2.setBackground(new Color(216,99,1));        
        }
        else{
            h1.setBackground(new Color(216,99,1));
            h2.setBackground(new Color(70,55,37));   
        }  
    }
    
    public void changeimage(JLabel button, String resourcecheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcecheimg));
        button.setIcon(aimg);
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        
        if(dashboard == true){
            
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/Images/menu_32px.png");
        }
        
        else{
            
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            changeimage(button, "/Images/menu_32px.png");
            
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        menuhide = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1500, 1090));
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        setLayout(new java.awt.BorderLayout());

        menu.setPreferredSize(new java.awt.Dimension(170, 450));
        menu.setLayout(new java.awt.BorderLayout());

        menuhide.setBackground(new java.awt.Color(36, 54, 101));
        menuhide.setMinimumSize(new java.awt.Dimension(170, 460));
        menuhide.setPreferredSize(new java.awt.Dimension(170, 460));
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 87, 87));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Users");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menuhide.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 30));

        menu.add(menuhide, java.awt.BorderLayout.LINE_START);

        add(menu, java.awt.BorderLayout.LINE_START);

        userProcessContainer.setBackground(new java.awt.Color(139, 216, 189));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
//        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise, system);
        if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Vendor){
            Create_VendorAdmin muajp = new Create_VendorAdmin(userProcessContainer, enterprise, system);
            userProcessContainer.add("ManageUserAccountJPanel", muajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.FulfillmentCenter){
            Create_FCAdmin muajp = new Create_FCAdmin(userProcessContainer, enterprise, system);
            userProcessContainer.add("ManageUserAccountJPanel", muajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Delivery){
            Create_DeliveryAdmin muajp = new Create_DeliveryAdmin(userProcessContainer, enterprise, system);
            userProcessContainer.add("ManageUserAccountJPanel", muajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.HubAndLastMile){
            Create_HubAndLMAdmin muajp = new Create_HubAndLMAdmin(userProcessContainer, enterprise, system);
            userProcessContainer.add("ManageUserAccountJPanel", muajp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
