/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.EnterpriseDelivery.Delivery;
import Business.EnterpriseVendor.Vendor;
import Business.Role.Customer;
import Business.Role.DeliveryAdmin;
import Business.Role.Dock;
import Business.Role.FirstMileDelivery;
import Business.Role.FulfillmentCenterAdmin;
import Business.Role.HubAndLastMileAdmin;
import Business.Role.HubMan;
import Business.Role.LastMileDelivery;
import Business.Role.LastMileMan;
import Business.Role.ManagerFMDeliveryMenAdmin;
import Business.Role.ManagerLMDeliveryMenAdmin;
import Business.Role.PickAndPack;
import Business.Role.Recieve;
import Business.Role.Stow;
import Business.Role.Sysadmin;
import Business.Role.VendorAdmin;
import Business.Role.VendorManager;
import Business.UserAccount.User;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import userinterface.CustomerRole.CustomerAreaJPanel;
import userinterface.FCRole.Inbound.RecieveAreaJPanel;
import userinterface.FCRole.Inbound.StowAreaJPanel;
import userinterface.FCRole.Outbound.DockManAreaJPanel;
import userinterface.FCRole.Outbound.PickAndPackAreaJPanel;
import userinterface.FMDeliveryRole.FMDeliveryMan.FMDeliveryManAreaJPanel;
import userinterface.FMDeliveryRole.FMDeliveryManagerAreaJPanel;
import userinterface.HubAndLastMileRole.HubAreaJPanel;
import userinterface.HubAndLastMileRole.LastMileAreaJPanel;
import userinterface.LMDeliveryRole.LMDeliveryMan.LMDeliveryManAreaJPanel;
import userinterface.LMDeliveryRole.LMDeliveryManagerAreaJPanel;
import userinterface.SysadminRole.AdminRole.AdminWorkAreaJPanel;
import userinterface.SysadminRole.SystemAdminWorkAreaJPanel;
import userinterface.VendorRole.VendorManagerPanel;

/**
 *
 * @author jayatipatel
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public String username;
    public String passord;
    public LoginPage() {
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        } catch (Exception ex) { 
            ex.printStackTrace(); 
        }
        initComponents();
        this.system = dB4OUtil.retrieveSystem();
        if(this.system==null){
            this.system=EcoSystem.getInstance();
        }
        this.setSize(800, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerSize(0);

        jPanel1.setBackground(new java.awt.Color(13, 24, 78));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(224, 89, 82));

        jPasswordField1.setBackground(new java.awt.Color(224, 89, 82));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("EnterPassword");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextField1.setBackground(new java.awt.Color(224, 89, 82));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Username");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setBackground(new java.awt.Color(224, 89, 82));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_icon-2.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jPasswordField1, jTextField1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jPasswordField1, jTextField1});

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        UserAccount auth = system.getUserAccountDirectory().authenticateUser(jTextField1.getText(), jPasswordField1.getText());// getUserAccountList() authenticateUser(userNameJTextField,passwordField);
        if(auth==null){
            System.out.println("Enter correct credentials");
            JOptionPane.showMessageDialog(this,"Enter correct credentials");
        }
        else if (auth.getRole()==User.Role.Customer){
            Customer customer = (Customer)auth.getUser();
            CustomerAreaJPanel yoyo = new CustomerAreaJPanel(customer);
            jSplitPane1.setRightComponent(yoyo);
            //Admin ad = (Admin)auth.getUser();
            //SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel1();
            //SystemAdmin yoyo = new SystemAdmin();
            //jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.Dock){
            Dock dockMan = (Dock)auth.getUser();
            DockManAreaJPanel yoyo = new DockManAreaJPanel(dockMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.FMDelivery){
            FirstMileDelivery fmDelivery = (FirstMileDelivery)auth.getUser();
            Delivery del=fmDelivery.getDeliveryByID();// getDelivery();
            FMDeliveryManAreaJPanel yoyo = new FMDeliveryManAreaJPanel(fmDelivery);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.HubManager){
            HubMan hub = (HubMan)auth.getUser();
            HubAreaJPanel yoyo = new HubAreaJPanel(hub);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.LMManager){
            LastMileMan lmAdmin = (LastMileMan)auth.getUser();
            LastMileAreaJPanel yoyo = new LastMileAreaJPanel(lmAdmin);
            jSplitPane1.setRightComponent(yoyo);
//            ManagerLMDeliveryMenAdmin managerDel=(ManagerLMDeliveryMenAdmin)auth.getUser();
//            LMDeliveryManagerAreaJPanel yoyo = new LMDeliveryManagerAreaJPanel(((ManagerLMDeliveryMenAdmin)auth.getUser()).getDelivery());
//            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.LMDelivery){
            LastMileDelivery lmDeliveryMan = (LastMileDelivery)auth.getUser();
            LMDeliveryManAreaJPanel yoyo = new LMDeliveryManAreaJPanel(lmDeliveryMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.PickAndPack){
            PickAndPack pickAndPackMan = (PickAndPack)auth.getUser();
            PickAndPackAreaJPanel yoyo = new PickAndPackAreaJPanel(pickAndPackMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.Recieve){
            Recieve recieverMan = (Recieve)auth.getUser();
            RecieveAreaJPanel yoyo = new RecieveAreaJPanel(recieverMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.Stow){
            Stow stowMan = (Stow)auth.getUser();
            StowAreaJPanel yoyo = new StowAreaJPanel(stowMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.SysAdmin){
            Sysadmin ad = (Sysadmin)auth.getUser();
            //SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel1();
            SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel(system);
            //SystemAdmin yoyo = new SystemAdmin();
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.VendorManager){
//            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(((Manager)auth.getUser()).getRestaurant());
            VendorManager vendorMan = (VendorManager)auth.getUser();
            Vendor vendor=vendorMan.getVendor();
            VendorManagerPanel yoyo = new VendorManagerPanel(vendor);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.FMDeliveryManager){
            ManagerFMDeliveryMenAdmin managerDel=(ManagerFMDeliveryMenAdmin)auth.getUser();
            FMDeliveryManagerAreaJPanel yoyo = new FMDeliveryManagerAreaJPanel(((ManagerFMDeliveryMenAdmin)auth.getUser()).getDelivery());
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.LMDeliveryManager){
            ManagerLMDeliveryMenAdmin managerDel=(ManagerLMDeliveryMenAdmin)auth.getUser();
            LMDeliveryManagerAreaJPanel yoyo = new LMDeliveryManagerAreaJPanel(((ManagerLMDeliveryMenAdmin)auth.getUser()).getDelivery());
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.DeliveryAdmin){
            DeliveryAdmin d = (DeliveryAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.HubAndLastMileAdmin){
            HubAndLastMileAdmin d = (HubAndLastMileAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==User.Role.VendorAdmin){
            VendorAdmin d = (VendorAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            jSplitPane1.setRightComponent(yoyo);
        }        
        else if(auth.getRole()==User.Role.FCAdmin){
            FulfillmentCenterAdmin d = (FulfillmentCenterAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            jSplitPane1.setRightComponent(yoyo);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
