/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.UserAccount.User.Role;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import Business.DB4OUtil.DB4OUtil;
import Business.ConfigureASystem;
import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.EnterpriseDelivery.Delivery;
import Business.EnterpriseVendor.Vendor;
import Business.Organization;
import Business.Role.Customer;
import Business.Role.DeliveryAdmin;
import Business.Role.DirectDelivery;
import Business.Role.Dock;
import Business.Role.FirstMileDelivery;
import Business.Role.FulfillmentCenterAdmin;
import Business.Role.HubAdmin;
import Business.Role.HubAndLastMileAdmin;
import Business.Role.HubMan;
import Business.Role.LastMileAdmin;
import Business.Role.LastMileDelivery;
import Business.Role.LastMileMan;
import Business.Role.ManagerDirectDeliveryMenAdmin;
import Business.Role.ManagerFMDeliveryMenAdmin;
import Business.Role.ManagerLMDeliveryMenAdmin;
import Business.Role.PickAndPack;
import Business.Role.Recieve;
import Business.Role.Stow;
import Business.Role.Sysadmin;
import Business.Role.VendorAdmin;
import Business.Role.VendorManager;
import Business.UserAccount.User;
import Business.UserAccount.User.Role;
import static Business.UserAccount.User.Role.DeliveryAdmin;
import static Business.UserAccount.User.Role.DirectDelivery;
import static Business.UserAccount.User.Role.DirectDeliveryManager;
import static Business.UserAccount.User.Role.HubAndLastMileAdmin;
import static Business.UserAccount.User.Role.VendorManager;
//import static Business.UserAccount.User.Role.Vendor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import userinterface.CustomerRole.CustomerAreaJPanel;
import userinterface.DirectDelivery.DirectDeliveryMan.DirectDeliveryManAreaJPanel;
import userinterface.DirectDeliveryN.DirectDeliveryManagerAreaJPanel;
import userinterface.FCRole.Outbound.DockManAreaJPanel;
import userinterface.FMDeliveryRole.FMDeliveryManagerAreaJPanel;
import userinterface.FMDeliveryRole.FMDeliveryMan.FMDeliveryManAreaJPanel;
import userinterface.HubAdminRole.HubAdminAreaJPanel;
import userinterface.LMAdminRole.LastMileAdminAreaJPanel;
import userinterface.LMDeliveryRole.LMDeliveryManagerAreaJPanel;
import userinterface.FCRole.Outbound.PickAndPackAreaJPanel;
import userinterface.FCRole.Inbound.RecieveAreaJPanel;
import userinterface.FCRole.Inbound.StowAreaJPanel;
import userinterface.HubAndLastMileRole.HubAreaJPanel;
import userinterface.HubAndLastMileRole.LastMileAreaJPanel;
import userinterface.LMDeliveryRole.LMDeliveryMan.LMDeliveryManAreaJPanel;
import userinterface.SysadminRole.AdminRole.AdminWorkAreaJPanel;
import userinterface.SysadminRole.Customer.Create_CustomerJPanel;
import userinterface.SysadminRole.ManageEnterpriseJPanel;
import userinterface.SysadminRole.ManageNetworkJPanel;
import userinterface.SysadminRole.SystemAdminWorkAreaJPanel;
import userinterface.SysadminRole.SystemAdminWorkAreaJPanel1;
import userinterface.VendorRole.VendorAreaJPanel;
import userinterface.VendorRole.VendorManagerPanel;

/**
 *
 * @author nisho
 */
public class MainJFrame extends javax.swing.JFrame {

    //
  
    //
    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public String username;
    public String passord;
    public MainJFrame() {
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        } catch (Exception ex) { 
            ex.printStackTrace(); 
        }
        initComponents();
        displayPicture();
        //nishok
        this.system = ConfigureASystem.configure();
//UNCOMMENT THIS AND COMMENT THE LAST LINE        
//this.system = dB4OUtil.retrieveSystem();
        if(this.system==null){
            this.system=EcoSystem.getInstance();
        }
        this.setSize(800, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        CreateCustAccButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iconimg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(36, 54, 101));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 100));

        loginJButton.setBackground(new java.awt.Color(255, 87, 87));
        loginJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginJButton.setForeground(new java.awt.Color(255, 255, 255));
        loginJButton.setText("Login");
        loginJButton.setBorder(null);
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        logoutJButton.setBackground(new java.awt.Color(255, 87, 87));
        logoutJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutJButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutJButton.setText("Logout");
        logoutJButton.setBorder(null);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        CreateCustAccButton.setBackground(new java.awt.Color(255, 87, 87));
        CreateCustAccButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateCustAccButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateCustAccButton.setText("Customer Registration");
        CreateCustAccButton.setBorder(null);
        CreateCustAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCustAccButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(loginJLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(userNameField))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateCustAccButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CreateCustAccButton, loginJButton, logoutJButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginJLabel)
                .addGap(94, 94, 94)
                .addComponent(CreateCustAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(672, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CreateCustAccButton, loginJButton, logoutJButton});

        jSplitPane1.setLeftComponent(jPanel1);

        container.setPreferredSize(new java.awt.Dimension(1500, 1000));

        jPanel2.setBackground(new java.awt.Color(139, 216, 189));
        jPanel2.setPreferredSize(new java.awt.Dimension(2000, 1000));

        jPanel3.setBackground(new java.awt.Color(0, 8, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Future of Supply Chain");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );

        jPanel4.setBackground(new java.awt.Color(0, 8, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Smart Inventory Manageement");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(29, 29, 29))
        );

        jPanel5.setBackground(new java.awt.Color(0, 8, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Drones impact on supply chain");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/video-camera.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        iconimg.setBackground(new java.awt.Color(36, 54, 101));

        jPanel6.setBackground(new java.awt.Color(36, 54, 101));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("OMNIBUS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 423, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(iconimg, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13))
                .addContainerGap(788, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO do authentication
        logoutJButton.setEnabled(true);
        UserAccount auth = system.getUserAccountDirectory().authenticateUser(userNameField.getText(), passwordField.getText());// getUserAccountList() authenticateUser(userNameJTextField,passwordField);
        if(auth==null){
            System.out.println("Enter correct credentials");
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><font color='red'>Enter correct credentials</font></h2></html>") , "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(this,"Enter correct credentials");
            
            //ask if you are a customer and want to create an account
            //create account page
            
        }
        else if (auth.getRole()==Role.Customer){
            Customer customer = (Customer)auth.getUser();
            CustomerAreaJPanel yoyo = new CustomerAreaJPanel(customer);
            jSplitPane1.setRightComponent(yoyo);
            //Admin ad = (Admin)auth.getUser();
            //SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel1();
            //SystemAdmin yoyo = new SystemAdmin();
            //jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.Dock){
            Dock dockMan = (Dock)auth.getUser();
            DockManAreaJPanel yoyo = new DockManAreaJPanel(dockMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.FMDelivery){
            FirstMileDelivery fmDelivery = (FirstMileDelivery)auth.getUser();
            Delivery del=fmDelivery.getDeliveryByID();// getDelivery();
            FMDeliveryManAreaJPanel yoyo = new FMDeliveryManAreaJPanel(fmDelivery);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.DirectDelivery){
            DirectDelivery dirDelivery = (DirectDelivery)auth.getUser();
            Delivery del=dirDelivery.getDeliveryByID();// getDelivery();
            DirectDeliveryManAreaJPanel yoyo = new DirectDeliveryManAreaJPanel(dirDelivery);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.DirectDeliveryManager){
            ManagerDirectDeliveryMenAdmin dirDeliveryMan = (ManagerDirectDeliveryMenAdmin)auth.getUser();
            //Delivery del=dirDeliveryMan.getDeliveryByID();// getDelivery();
            DirectDeliveryManagerAreaJPanel yoyo = new DirectDeliveryManagerAreaJPanel(dirDeliveryMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.HubManager){
            HubMan hub = (HubMan)auth.getUser();
            HubAreaJPanel yoyo = new HubAreaJPanel(hub);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.LMManager){
            LastMileMan lmAdmin = (LastMileMan)auth.getUser();
            LastMileAreaJPanel yoyo = new LastMileAreaJPanel(lmAdmin);
            jSplitPane1.setRightComponent(yoyo);
            
//            ManagerLMDeliveryMenAdmin managerDel=(ManagerLMDeliveryMenAdmin)auth.getUser();
//            LMDeliveryManagerAreaJPanel yoyo = new LMDeliveryManagerAreaJPanel(((ManagerLMDeliveryMenAdmin)auth.getUser()).getDelivery());
//            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.LMDelivery){
            LastMileDelivery lmDeliveryMan = (LastMileDelivery)auth.getUser();
            LMDeliveryManAreaJPanel yoyo = new LMDeliveryManAreaJPanel(lmDeliveryMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.PickAndPack){
            PickAndPack pickAndPackMan = (PickAndPack)auth.getUser();
            PickAndPackAreaJPanel yoyo = new PickAndPackAreaJPanel(pickAndPackMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.Recieve){
            Recieve recieverMan = (Recieve)auth.getUser();
            RecieveAreaJPanel yoyo = new RecieveAreaJPanel(recieverMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.Stow){
            Stow stowMan = (Stow)auth.getUser();
            StowAreaJPanel yoyo = new StowAreaJPanel(stowMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.SysAdmin){
            Sysadmin ad = (Sysadmin)auth.getUser();
            //SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel1();
            SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel(system);
            //SystemAdmin yoyo = new SystemAdmin();
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.VendorManager){
//            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(((Manager)auth.getUser()).getRestaurant()); 
            
            VendorManager vendorMan = (VendorManager)auth.getUser();
            Vendor vendor=vendorMan.getVendor();
            VendorManagerPanel yoyo = new VendorManagerPanel(vendor);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.FMDeliveryManager){
            ManagerFMDeliveryMenAdmin managerDel=(ManagerFMDeliveryMenAdmin)auth.getUser();
            FMDeliveryManagerAreaJPanel yoyo = new FMDeliveryManagerAreaJPanel(((ManagerFMDeliveryMenAdmin)auth.getUser()).getDelivery());
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.LMDeliveryManager){
            ManagerLMDeliveryMenAdmin managerDel=(ManagerLMDeliveryMenAdmin)auth.getUser();
            LMDeliveryManagerAreaJPanel yoyo = new LMDeliveryManagerAreaJPanel(((ManagerLMDeliveryMenAdmin)auth.getUser()).getDelivery());
            jSplitPane1.setRightComponent(yoyo);
        }
        
        
        
        else if(auth.getRole()==Role.DeliveryAdmin){
            DeliveryAdmin d = (DeliveryAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.HubAndLastMileAdmin){
            HubAndLastMileAdmin d = (HubAndLastMileAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.VendorAdmin){
            VendorAdmin d = (VendorAdmin)auth.getUser();
            
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }        
        else if(auth.getRole()==Role.FCAdmin){
            FulfillmentCenterAdmin d = (FulfillmentCenterAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }
      //get username, password from frame
        //pass these values to Ecosystem.UserAccountDirectory.AuthenticateUser()
        //If result is not null, get the user role from the returned object and
        //direct him/her to the appropriate workflow
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        //CardLayout crdLyt = (CardLayout) container.getLayout();
        //crdLyt.next(container);
        //dB4OUtil.storeSystem(system);
        jSplitPane1.setRightComponent(container);
        //logoutJButton.setEnabled(true);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void CreateCustAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCustAccButtonActionPerformed
        // TODO add your handling code here:
        Create_CustomerJPanel yoyo = new Create_CustomerJPanel();
        jSplitPane1.setRightComponent(yoyo);
    }//GEN-LAST:event_CreateCustAccButtonActionPerformed

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        try {
             //TODO add your handling code here:
            Desktop.getDesktop().open(new File("src\\Images\\SupplyChainFuture.mp4"));
        } 
        catch (IOException ex) {
        
            System.out.print("Video not present");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        try {
             //TODO add your handling code here:
            Desktop.getDesktop().open(new File("src\\Images\\InventoryManagement.mp4"));
        } 
        catch (IOException ex) {
        
            System.out.print("Video not present");
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        try {
             //TODO add your handling code here:
            Desktop.getDesktop().open(new File("src\\Images\\DronesOnShippingIndustry.mp4"));
        } 
        catch (IOException ex) {
        
            System.out.print("Video not present");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCustAccButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel iconimg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
 private void displayPicture(){

        scaleIcon(219, 164, "F:\\AED_Final\\AED_FinalProject\\RapidExpress\\src\\uimages\\imageProj.jpeg", iconimg);
    }
   
    public void scaleIcon(int Width, int height, String imgPath, javax.swing.JLabel iconimg){
        File file = new File(imgPath);
        String absolutePath = file.getAbsolutePath();
        ImageIcon image = new ImageIcon(absolutePath);
        System.out.println(absolutePath);
        Image icon = image.getImage();
        icon = icon.getScaledInstance(Width, height, Image.SCALE_SMOOTH);
        image = new ImageIcon(icon);
        iconimg.setIcon(image);
        iconimg.setText("");
    }

}

