/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.UserAccount.User.Role;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import Business.DB4OUtil.DB4OUtil;
import Business.ConfigureASystem;
import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.EnterpriseDelivery.Delivery;
import Business.EnterpriseVendor.Vendor;
import Business.Organization;
import Business.Role.Customer;
import Business.Role.DeliveryAdmin;
import Business.Role.Dock;
import Business.Role.FirstMileDelivery;
import Business.Role.FulfillmentCenterAdmin;
import Business.Role.HubAdmin;
import Business.Role.HubAndLastMileAdmin;
import Business.Role.HubMan;
import Business.Role.LastMileAdmin;
import Business.Role.LastMileDelivery;
import Business.Role.LastMileMan;
import Business.Role.ManagerFMDeliveryMenAdmin;
import Business.Role.ManagerLMDeliveryMenAdmin;
import Business.Role.PickAndPack;
import Business.Role.Recieve;
import Business.Role.Stow;
import Business.Role.Sysadmin;
import Business.Role.VendorAdmin;
import Business.Role.VendorManager;
import Business.UserAccount.User;
import Business.UserAccount.User.Role;
import static Business.UserAccount.User.Role.DeliveryAdmin;
import static Business.UserAccount.User.Role.HubAndLastMileAdmin;
import static Business.UserAccount.User.Role.VendorManager;
//import static Business.UserAccount.User.Role.Vendor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import userinterface.CustomerRole.CustomerAreaJPanel;
import userinterface.FCRole.Outbound.DockManAreaJPanel;
import userinterface.FMDeliveryRole.FMDeliveryManagerAreaJPanel;
import userinterface.FMDeliveryRole.FMDeliveryMan.FMDeliveryManAreaJPanel;
import userinterface.HubAdminRole.HubAdminAreaJPanel;
import userinterface.LMAdminRole.LastMileAdminAreaJPanel;
import userinterface.LMDeliveryRole.LMDeliveryManagerAreaJPanel;
import userinterface.FCRole.Outbound.PickAndPackAreaJPanel;
import userinterface.FCRole.Inbound.RecieveAreaJPanel;
import userinterface.FCRole.Inbound.StowAreaJPanel;
import userinterface.HubAndLastMileRole.HubAreaJPanel;
import userinterface.HubAndLastMileRole.LastMileAreaJPanel;
import userinterface.LMDeliveryRole.LMDeliveryMan.LMDeliveryManAreaJPanel;
import userinterface.SysadminRole.AdminRole.AdminWorkAreaJPanel;
import userinterface.SysadminRole.Customer.Create_CustomerJPanel;
import userinterface.SysadminRole.ManageEnterpriseJPanel;
import userinterface.SysadminRole.ManageNetworkJPanel;
import userinterface.SysadminRole.SystemAdminWorkAreaJPanel;
import userinterface.SysadminRole.SystemAdminWorkAreaJPanel1;
import userinterface.VendorRole.VendorAreaJPanel;
import userinterface.VendorRole.VendorManagerPanel;

/**
 *
 * @author nisho
 */
public class MainJFrame extends javax.swing.JFrame {

    //
  
    //
    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public String username;
    public String passord;
    public MainJFrame() {
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        } catch (Exception ex) { 
            ex.printStackTrace(); 
        }
        initComponents();
        
        //nishok
        //this.system = ConfigureASystem.configure();
//UNCOMMENT THIS AND COMMENT THE LAST LINE        
this.system = dB4OUtil.retrieveSystem();
        if(this.system==null){
            this.system=EcoSystem.getInstance();
        }
        this.setSize(800, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        CreateCustAccButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(36, 54, 101));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 100));

        loginJButton.setBackground(new java.awt.Color(255, 87, 87));
        loginJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginJButton.setForeground(new java.awt.Color(255, 255, 255));
        loginJButton.setText("Login");
        loginJButton.setBorder(null);
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        logoutJButton.setBackground(new java.awt.Color(255, 87, 87));
        logoutJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutJButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutJButton.setText("Logout");
        logoutJButton.setBorder(null);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        CreateCustAccButton.setBackground(new java.awt.Color(255, 87, 87));
        CreateCustAccButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateCustAccButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateCustAccButton.setText("Customer Registration");
        CreateCustAccButton.setBorder(null);
        CreateCustAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCustAccButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(loginJLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(userNameField))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateCustAccButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CreateCustAccButton, loginJButton, logoutJButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginJLabel)
                .addGap(94, 94, 94)
                .addComponent(CreateCustAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(662, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CreateCustAccButton, loginJButton, logoutJButton});

        jSplitPane1.setLeftComponent(jPanel1);

        container.setPreferredSize(new java.awt.Dimension(1500, 1000));

        jPanel2.setBackground(new java.awt.Color(139, 216, 189));
        jPanel2.setForeground(new java.awt.Color(102, 204, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 1000));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1483, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1483, Short.MAX_VALUE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO do authentication
        logoutJButton.setEnabled(true);
        UserAccount auth = system.getUserAccountDirectory().authenticateUser(userNameField.getText(), passwordField.getText());// getUserAccountList() authenticateUser(userNameJTextField,passwordField);
        if(auth==null){
            System.out.println("Enter correct credentials");
            JOptionPane.showMessageDialog(this,"Enter correct credentials");
            
            //ask if you are a customer and want to create an account
            //create account page
            
        }
        else if (auth.getRole()==Role.Customer){
            Customer customer = (Customer)auth.getUser();
            CustomerAreaJPanel yoyo = new CustomerAreaJPanel(customer);
            jSplitPane1.setRightComponent(yoyo);
            //Admin ad = (Admin)auth.getUser();
            //SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel1();
            //SystemAdmin yoyo = new SystemAdmin();
            //jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.Dock){
            Dock dockMan = (Dock)auth.getUser();
            DockManAreaJPanel yoyo = new DockManAreaJPanel(dockMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.FMDelivery){
            FirstMileDelivery fmDelivery = (FirstMileDelivery)auth.getUser();
            Delivery del=fmDelivery.getDeliveryByID();// getDelivery();
            FMDeliveryManAreaJPanel yoyo = new FMDeliveryManAreaJPanel(fmDelivery);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.HubManager){
            HubMan hub = (HubMan)auth.getUser();
            HubAreaJPanel yoyo = new HubAreaJPanel(hub);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.LMManager){
            LastMileMan lmAdmin = (LastMileMan)auth.getUser();
            LastMileAreaJPanel yoyo = new LastMileAreaJPanel(lmAdmin);
            jSplitPane1.setRightComponent(yoyo);
            
//            ManagerLMDeliveryMenAdmin managerDel=(ManagerLMDeliveryMenAdmin)auth.getUser();
//            LMDeliveryManagerAreaJPanel yoyo = new LMDeliveryManagerAreaJPanel(((ManagerLMDeliveryMenAdmin)auth.getUser()).getDelivery());
//            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.LMDelivery){
            LastMileDelivery lmDeliveryMan = (LastMileDelivery)auth.getUser();
            LMDeliveryManAreaJPanel yoyo = new LMDeliveryManAreaJPanel(lmDeliveryMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.PickAndPack){
            PickAndPack pickAndPackMan = (PickAndPack)auth.getUser();
            PickAndPackAreaJPanel yoyo = new PickAndPackAreaJPanel(pickAndPackMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.Recieve){
            Recieve recieverMan = (Recieve)auth.getUser();
            RecieveAreaJPanel yoyo = new RecieveAreaJPanel(recieverMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.Stow){
            Stow stowMan = (Stow)auth.getUser();
            StowAreaJPanel yoyo = new StowAreaJPanel(stowMan);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.SysAdmin){
            Sysadmin ad = (Sysadmin)auth.getUser();
            //SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel1();
            SystemAdminWorkAreaJPanel yoyo = new SystemAdminWorkAreaJPanel(system);
            //SystemAdmin yoyo = new SystemAdmin();
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.VendorManager){
//            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(((Manager)auth.getUser()).getRestaurant()); 
            
            VendorManager vendorMan = (VendorManager)auth.getUser();
            Vendor vendor=vendorMan.getVendor();
            VendorManagerPanel yoyo = new VendorManagerPanel(vendor);
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.FMDeliveryManager){
            ManagerFMDeliveryMenAdmin managerDel=(ManagerFMDeliveryMenAdmin)auth.getUser();
            FMDeliveryManagerAreaJPanel yoyo = new FMDeliveryManagerAreaJPanel(((ManagerFMDeliveryMenAdmin)auth.getUser()).getDelivery());
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.LMDeliveryManager){
            ManagerLMDeliveryMenAdmin managerDel=(ManagerLMDeliveryMenAdmin)auth.getUser();
            LMDeliveryManagerAreaJPanel yoyo = new LMDeliveryManagerAreaJPanel(((ManagerLMDeliveryMenAdmin)auth.getUser()).getDelivery());
            jSplitPane1.setRightComponent(yoyo);
        }
        
        
        
        else if(auth.getRole()==Role.DeliveryAdmin){
            DeliveryAdmin d = (DeliveryAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.HubAndLastMileAdmin){
            HubAndLastMileAdmin d = (HubAndLastMileAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }
        else if(auth.getRole()==Role.VendorAdmin){
            VendorAdmin d = (VendorAdmin)auth.getUser();
            
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }        
        else if(auth.getRole()==Role.FCAdmin){
            FulfillmentCenterAdmin d = (FulfillmentCenterAdmin)auth.getUser();
            AdminWorkAreaJPanel yoyo = new AdminWorkAreaJPanel(d);
            
            jSplitPane1.setRightComponent(yoyo);
        }
      //get username, password from frame
        //pass these values to Ecosystem.UserAccountDirectory.AuthenticateUser()
        //If result is not null, get the user role from the returned object and
        //direct him/her to the appropriate workflow
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        //CardLayout crdLyt = (CardLayout) container.getLayout();
        //crdLyt.next(container);
        //dB4OUtil.storeSystem(system);
        jSplitPane1.setRightComponent(container);
        //logoutJButton.setEnabled(true);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void CreateCustAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCustAccButtonActionPerformed
        // TODO add your handling code here:
        Create_CustomerJPanel yoyo = new Create_CustomerJPanel();
        jSplitPane1.setRightComponent(yoyo);
    }//GEN-LAST:event_CreateCustAccButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCustAccButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
